export const serviceAccorderie = [
  "Accompagnement rendez-vous divers",
  "Accompagnement rendez-vous médicaux",
  "Accompagnement démarches médicales",
  "Accompagnement démarches suite é un décés",
  "Accompagnement magasinage",
  "Commissions é votre place",
  "Accompagnement épicerie",
  "Accompagnement commerces avec carte de membre",
  "Accompagnement marche",
  "Accompagnement musée",
  "Accompagnement raquette",
  "Garde d'enfants é votre maison",
  "Garde d'enfants é ma maison",
  "Garde d'enfants é ma maison avec les miens",
  "Garde de maison (home-sitting)",
  "Visite maison lors d'absence",
  "Garde d'animaux é ma maison",
  "Garde d'animaux é votre maison",
  "Promenade chien",
  "Soins chat",
  "Toilettage chien",
  "Aide pour remplir formulaires",
  "Conseils démarrage entreprise",
  "Tenue de livres comptables",
  "Rapport d'impét personnel",
  "Conseils budgétaires",
  "Rédaction Curriculum vitae",
  "Recherche d'emploi",
  "Organisation et animation groupes de discussion",
  "Organisation événements sociaux",
  "Classement documents",
  "Communication interne",
  "Aide démarches juridiques",
  "Initiation générale é l'informatique",
  "Initiation Word",
  "Initiation Excel",
  "Initiation tablettes électroniques / iPad",
  "Initiation et aide Espace membre",
  "Mise en page sur ordinateur",
  "Traitement de texte",
  "Tableaux Excel",
  "Montage PowerPoint",
  "Utilisation Illustrator",
  "Numérisation photos",
  "Initiation é Internet et courriel",
  "Recherche Internet",
  "Conception site web",
  "Installation Internet",
  "Assistance probléme Internet",
  "Initiation médias sociaux sur Internet",
  "Dépannage pour ordinateurs P.C.",
  "Dépannage pour ordinateurs Macintosh",
  "Installation de logiciels",
  "Dépannage disque dur",
  "Optimisation systéme d'exploitation (software)",
  "Optimisation matériel informatique (hardware)",
  "Transcription enregistrement audio (verbatim)",
  "Réseau informatique sans fil é domicile",
  "Initiation cellulaires / téléphones intelligents",
  "Assistance achat matériel informatique",
  "Transport besoins divers",
  "Transport pour les courses",
  "Transport moyenne distance",
  "Transport de matériel avec voiture",
  "Transport avec camionnette",
  "Transport avec remorque",
  "Des bras pour gros déménagement",
  "Des bras pour moyen déménagement",
  "Des bras pour petit déménagement",
  "Aide pour préparer déménagement",
  "Aide pour aménager",
  "Ménage léger",
  "Lavage vitres",
  "Peinture intérieure",
  "Peinture extérieure",
  "Conseils pour travaux de peinture / teinture",
  "Bricoleur pour petits travaux",
  "Menus travaux ébénisterie",
  "Menus travaux plomberie",
  "Menus travaux électricité",
  "Menus travaux soudure",
  "Aide pour rénovation",
  "Conseils pour autoconstruction",
  "Gestion projet de rénovation",
  "Conseils pour décoration intérieure",
  "Réparation de meubles",
  "Restauration ou fabrication de petits meubles",
  "Aide pour fabrication de meubles rustiques",
  "Réparations de petits moteurs électriques",
  "Réparation électroménagers",
  "Réparation petits appareils électriques",
  "Réparation machine é coudre",
  "Réparation appareils électroniques",
  "Entretien ou réparation automobile",
  "Lavage de voiture",
  "Travail sur carosserie auto",
  "Changement de pneus",
  "Réparation vélos",
  "Aide pour jardinage",
  "Entretien de plates-bandes",
  "Création ou élaboration d'un potager",
  "Informations plantes potagéres",
  "Travaux d'aménagement de terrains",
  "Aménagement paysager",
  "Conseils pour soins des arbres",
  "Conseils en aménagement paysager",
  "Taille de haie / arbustes",
  "Travaux d'entretien de terrains",
  "Nettoyage saisonnier de terrains",
  "Petit déneigement",
  "Tonte de gazon",
  "Aide cordage de bois",
  "Récupération outils usagés",
  "Travaux divers en hauteur",
  "Aide au désencombrement",
  "Accompagnement cuisine",
  "Aide pour cuisiner",
  "Préparation biscuits",
  "Préparation muffins santé",
  "Confection pétisserie",
  "Initiation fabrication de pain",
  "Conseils cuisine végétarienne ou végétalienne",
  "Réparation ou restauration d'objets décoratifs",
  "Conception jouets en fibres naturelles",
  "Confection cartes de souhait artisanales",
  "Emballage cadeau",
  "Fabrication de bijoux",
  "Réparation bijoux",
  "Confection bijoux en matiéres recyclées",
  "Fabrication vétements",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Modifications vétements",
  "Couture de type industriel",
  "Réparation coussins, rideaux, housses douillettes",
  "Confection sacs réutilisables en tissu",
  "Initiation usage de machine é coudre",
  "Fabrication vétements en tricot",
  "Fabrication objets en macramé",
  "Foire artisanale",
  "- Foire de l'Artisanat",
  "Rédaction textes en franéais",
  "Correction textes en franéais",
  "Correction textes en anglais",
  "Apprentissage de la guitare",
  "Chansonnier pour spectacle",
  "Film événements spéciaux",
  "Montage vidéo",
  "Réalisation vidéo",
  "Prise de photos portrait",
  "Initiation photographie numérique",
  "Initiation retouche de photo informatisée",
  "Initiation aquarelle",
  "Illustration",
  "Portraitiste",
  "Initiation orientation avec cartes et boussole",
  "Initiation danse sociale",
  "Clown pour fétes d'enfants ou événements",
  "Animation fétes et événements",
  "Organisation petits événements",
  "Références fibromyalgie",
  "Bilan de santé naturopathique",
  "Réflexologie",
  "Reiki",
  "Harmonisation énergétique",
  "Massothérapie thérapeutique",
  "Massothérapie sur chaise",
  "Maquillage",
  "AccordeurE inscritE é la location solidaire (é titre d'information)",
  "Conseils consommation responsable",
  "Aide dénichage d'aubaines",
  "Prét d'un objet location solidaire",
  "Accueil/réception permanence Accorderie",
  "Envoi postal pour L'Accorderie",
  "Facteur et factrice d'un jour",
  "Sondages pour L'Accorderie",
  "Vérification comptable de L'Accorderie",
  "Comptabilité de L'Accorderie",
  "Rencontre de travail comité accueil",
  "Rencontre de travail comité gestion",
  "Communications pour L'Accorderie",
  "Comité communications - rencontre et téches",
  "Comité accueil - coordination",
  "Comité accueil - équipe téléphone",
  "Comité mobilisation - rencontre et téches",
  "Comité Améliorons l'Accorderie",
  "Rencontre représentants de comités",
  "Animation kiosque pour L'Accorderie",
  "Représentation de L'Accorderie",
  "Session d'accueil de L'Accorderie",
  "Tâches pour Fétes ou 5 é 7 de L'Accorderie",
  "Formation pour L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "Rencontre comité Vie associative et gestion de l'échange",
  "élaboration du Journal / du Bottin",
  "Mise à jour de la liste des membres",
  "Tâches manuelles pour L'Accorderie",
  "Tâches cléricales pour L'Accorderie",
  "Graphisme pour L'Accorderie",
  "Développement d'outils pour L'Accorderie",
  "Rencontre de travail aménagement / entretien des locaux",
  "Transport pour L'Accorderie",
  "Rencontre de travail comité de financement",
  "Tâches cléricales comité de financement",
  "Tâches activité de financement",
  "Tâche contact communautaire",
  "Rencontre comité jardin collectif",
  "Entretien jardin collectif",
  "Animation jardin collectif",
  "Tâches diverses - Café",
  "Organisation et animation d'activités - milieux de vie dynamisés",
  "Réseau d'éclaireurs",
  "Projet Résilience",
  "Soutien en informatique",
  "Démarrage du projet",
  "Production de sacs écologiques pour Accorderie",
  "APIC-Accompagnement d'aénés",
  "Appels de courtoisie",
  "Aide aux courses",
  "Bon cadeau",
  "Transfert d'heures",
  "Remboursement",
  "Accompagnement rendez-vous divers",
  "Accompagnement rendez-vous médicaux",
  "Garde d'enfants é ma maison avec les miens",
  "Aide pour remplir formulaires",
  "Rapport d'impét personnel",
  "Recherche d'emploi",
  "Organisation événements sociaux",
  "Initiation générale é l'informatique",
  "Initiation et aide Espace membre",
  "Mise en page sur ordinateur",
  "Utilisation Illustrator",
  "Initiation é Internet et courriel",
  "Initiation médias sociaux sur Internet",
  "Dépannage pour ordinateurs P.C.",
  "Transport besoins divers",
  "Transport avec camionnette",
  "Transport avec remorque",
  "Des bras pour gros déménagement",
  "Des bras pour moyen déménagement",
  "Des bras pour petit déménagement",
  "Aide pour aménager",
  "Ménage léger",
  "Peinture intérieure",
  "Conseils pour travaux de peinture / teinture",
  "Bricoleur pour petits travaux",
  "Menus travaux plomberie",
  "Menus travaux électricité",
  "Conseils pour autoconstruction",
  "Restauration ou fabrication de petits meubles",
  "Aide pour fabrication de meubles rustiques",
  "Lavage de voiture",
  "Travail sur carosserie auto",
  "Changement de pneus",
  "Aide pour jardinage",
  "Entretien de plates-bandes",
  "Création ou élaboration d'un potager",
  "Informations plantes potagéres",
  "Taille de haie / arbustes",
  "Nettoyage saisonnier de terrains",
  "Aide pour cuisiner",
  "Cuisine plats ou repas",
  "Préparation lunchs",
  "Confection desserts pour événements",
  "Préparation biscuits",
  "Préparation muffins",
  "Préparation muffins santé",
  "Confection pétisserie",
  "Conception jouets en fibres naturelles",
  "Confection cartes de souhait artisanales",
  "Emballage cadeau",
  "Fabrication de bijoux",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Confection sacs réutilisables en tissu",
  "Fabrication objets en macramé",
  "Correction textes en franéais",
  "Film événements spéciaux",
  "Portraitiste",
  "Bilan de santé naturopathique",
  "Réflexologie",
  "Harmonisation énergétique",
  "Massothérapie de détente",
  "Coupe cheveux",
  "Conseils consommation responsable",
  "Aide dénichage d'aubaines",
  "Accueil/réception permanence Accorderie",
  "Sondages pour L'Accorderie",
  "Rencontre de travail comité accueil",
  "Communications pour L'Accorderie",
  "Animation kiosque pour L'Accorderie",
  "Session d'accueil de L'Accorderie",
  "Tâches pour Fétes ou 5 é 7 de L'Accorderie",
  "Formation pour L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "Rencontre comité Vie associative et gestion de l'échange",
  "Entretien ménager des locaux",
  "Tâches cléricales pour L'Accorderie",
  "Rencontre de travail comité de financement",
  "Tâches activité de financement",
  "Organisation et animation d'activités - milieux de vie dynamisés",
  "Démarrage du projet",
  "Production de sacs écologiques pour Accorderie",
  "Aide aux courses",
  "Remboursement",
  "Accompagnement rendez-vous divers",
  "Accompagnement rendez-vous médicaux",
  "Garde d'enfants é ma maison avec les miens",
  "Aide pour remplir formulaires",
  "Rapport d'impét personnel",
  "Recherche d'emploi",
  "Organisation événements sociaux",
  "Initiation générale é l'informatique",
  "Initiation et aide Espace membre",
  "Mise en page sur ordinateur",
  "Utilisation Illustrator",
  "Initiation é Internet et courriel",
  "Initiation médias sociaux sur Internet",
  "Dépannage pour ordinateurs P.C.",
  "Transport besoins divers",
  "Transport avec camionnette",
  "Transport avec remorque",
  "Des bras pour gros déménagement",
  "Des bras pour moyen déménagement",
  "Des bras pour petit déménagement",
  "Aide pour aménager",
  "Ménage léger",
  "Peinture intérieure",
  "Conseils pour travaux de peinture / teinture",
  "Bricoleur pour petits travaux",
  "Menus travaux plomberie",
  "Menus travaux électricité",
  "Conseils pour autoconstruction",
  "Restauration ou fabrication de petits meubles",
  "Aide pour fabrication de meubles rustiques",
  "Lavage de voiture",
  "Travail sur carosserie auto",
  "Changement de pneus",
  "Aide pour jardinage",
  "Entretien de plates-bandes",
  "Création ou élaboration d'un potager",
  "Informations plantes potagéres",
  "Taille de haie / arbustes",
  "Nettoyage saisonnier de terrains",
  "Aide pour cuisiner",
  "Cuisine plats ou repas",
  "Préparation lunchs",
  "Confection desserts pour événements",
  "Préparation biscuits",
  "Préparation muffins",
  "Préparation muffins santé",
  "Confection pétisserie",
  "Conception jouets en fibres naturelles",
  "Confection cartes de souhait artisanales",
  "Emballage cadeau",
  "Fabrication de bijoux",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Confection sacs réutilisables en tissu",
  "Fabrication objets en macramé",
  "Correction textes en franéais",
  "Film événements spéciaux",
  "Portraitiste",
  "Bilan de santé naturopathique",
  "Réflexologie",
  "Harmonisation énergétique",
  "Massothérapie de détente",
  "Coupe cheveux",
  "Conseils consommation responsable",
  "Aide dénichage d'aubaines",
  "Accueil/réception permanence Accorderie",
  "Sondages pour L'Accorderie",
  "Rencontre de travail comité accueil",
  "Communications pour L'Accorderie",
  "Animation kiosque pour L'Accorderie",
  "Session d'accueil de L'Accorderie",
  "Tâches pour Fétes ou 5 é 7 de L'Accorderie",
  "Formation pour L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "Rencontre comité Vie associative et gestion de l'échange",
  "Entretien ménager des locaux",
  "Tâches cléricales pour L'Accorderie",
  "Rencontre de travail comité de financement",
  "Tâches activité de financement",
  "Organisation et animation d'activités - milieux de vie dynamisés",
  "Démarrage du projet",
  "Production de sacs écologiques pour Accorderie",
  "Aide aux courses",
  "Remboursement",
  "Accompagnement rendez-vous médicaux",
  "Correction textes en franéais",
  "Tâches manuelles pour L'Accorderie",
  "Accompagnement rendez-vous médicaux",
  "Correction textes en franéais",
  "Tâches manuelles pour L'Accorderie",
  "Communication interne",
  "Transport avec remorque",
  "Des bras pour gros déménagement",
  "Menus travaux électricité",
  "Aide cordage de bois",
  "Conseils cuisine végétarienne ou végétalienne",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Correction textes en franéais",
  "Conversation espagnole",
  "Initiation orientation avec cartes et boussole",
  "Comité Améliorons l'Accorderie",
  "Tâches activité de financement",
  "Communication interne",
  "Transport avec remorque",
  "Des bras pour gros déménagement",
  "Menus travaux électricité",
  "Aide cordage de bois",
  "Conseils cuisine végétarienne ou végétalienne",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Correction textes en franéais",
  "Conversation espagnole",
  "Initiation orientation avec cartes et boussole",
  "Comité Améliorons l'Accorderie",
  "Tâches activité de financement",
  "Accompagnement épicerie",
  "Accompagnement raquette",
  "Tableaux Excel",
  "Dépannage pour ordinateurs P.C.",
  "Transport besoins divers",
  "Transport pour les courses",
  "Des bras pour moyen déménagement",
  "Aide pour rénovation",
  "Aide pour jardinage",
  "Travaux d'entretien de terrains",
  "Nettoyage saisonnier de terrains",
  "Petit déneigement",
  "Tonte de gazon",
  "Accompagnement cuisine",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Rédaction textes en franéais",
  "Vérification comptable de L'Accorderie",
  "Communications pour L'Accorderie",
  "Représentation de L'Accorderie",
  "Formation pour L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "Tâches manuelles pour L'Accorderie",
  "Tâches cléricales pour L'Accorderie",
  "Transport pour L'Accorderie",
  "Tâches cléricales comité de financement",
  "Accompagnement épicerie",
  "Accompagnement raquette",
  "Tableaux Excel",
  "Dépannage pour ordinateurs P.C.",
  "Transport besoins divers",
  "Transport pour les courses",
  "Des bras pour moyen déménagement",
  "Aide pour rénovation",
  "Aide pour jardinage",
  "Travaux d'entretien de terrains",
  "Nettoyage saisonnier de terrains",
  "Petit déneigement",
  "Tonte de gazon",
  "Accompagnement cuisine",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Rédaction textes en franéais",
  "Vérification comptable de L'Accorderie",
  "Communications pour L'Accorderie",
  "Représentation de L'Accorderie",
  "Formation pour L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "Tâches manuelles pour L'Accorderie",
  "Tâches cléricales pour L'Accorderie",
  "Transport pour L'Accorderie",
  "Tâches cléricales comité de financement",
  "Accompagnement commerces avec carte de membre",
  "Accompagnement marche",
  "Accompagnement musée",
  "Garde d'animaux é ma maison",
  "Promenade chien",
  "Aide pour remplir formulaires",
  "Rapport d'impét personnel",
  "Conseils budgétaires",
  "Initiation générale é l'informatique",
  "Initiation Excel",
  "Initiation tablettes électroniques / iPad",
  "Initiation et aide Espace membre",
  "Traitement de texte",
  "Montage PowerPoint",
  "Numérisation photos",
  "Initiation é Internet et courriel",
  "Conception site web",
  "Dépannage pour ordinateurs P.C.",
  "Dépannage pour ordinateurs Macintosh",
  "Installation de logiciels",
  "Dépannage disque dur",
  "Optimisation systéme d'exploitation (software)",
  "Transport besoins divers",
  "Transport pour les courses",
  "Transport moyenne distance",
  "Transport avec remorque",
  "Des bras pour moyen déménagement",
  "Des bras pour petit déménagement",
  "Aide pour préparer déménagement",
  "Ménage léger",
  "Lavage vitres",
  "Bricoleur pour petits travaux",
  "Menus travaux ébénisterie",
  "Aide pour rénovation",
  "Réparation de meubles",
  "Réparation appareils électroniques",
  "Entretien ou réparation automobile",
  "Lavage de voiture",
  "Réparation vélos",
  "Aide pour jardinage",
  "Conseils pour soins des arbres",
  "Conseils en aménagement paysager",
  "Travaux d'entretien de terrains",
  "Nettoyage saisonnier de terrains",
  "Cuisine plats ou repas",
  "Préparation repas é congeler",
  "Réparation ou restauration d'objets décoratifs",
  "Réparation bijoux",
  "Petites réparations vétements",
  "Rédaction textes en franéais",
  "Correction textes en anglais",
  "Apprentissage de l'anglais",
  "Conversation anglaise",
  "Initiation danse sociale",
  "Animation fétes et événements",
  "Reiki",
  "Massothérapie thérapeutique",
  "Massothérapie de détente",
  "Coupe cheveux",
  "Maquillage",
  "AccordeurE inscritE é la location solidaire (é titre d'information)",
  "Prét d'un objet location solidaire",
  "Accueil/réception permanence Accorderie",
  "Envoi postal pour L'Accorderie",
  "Facteur et factrice d'un jour",
  "Vérification comptable de L'Accorderie",
  "Rencontre de travail comité accueil",
  "Rencontre de travail comité gestion",
  "Communications pour L'Accorderie",
  "Comité accueil - coordination",
  "Rencontre représentants de comités",
  "Représentation de L'Accorderie",
  "Session d'accueil de L'Accorderie",
  "Formation pour L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "Mise à jour de la liste des membres",
  "Tâches cléricales pour L'Accorderie",
  "Développement d'outils pour L'Accorderie",
  "Rencontre de travail aménagement / entretien des locaux",
  "Tâches cléricales comité de financement",
  "Accompagnement rendez-vous divers",
  "Accompagnement rendez-vous médicaux",
  "Accompagnement commerces avec carte de membre",
  "Accompagnement marche",
  "Accompagnement musée",
  "Garde d'animaux é ma maison",
  "Promenade chien",
  "Aide pour remplir formulaires",
  "Rapport d'impét personnel",
  "Conseils budgétaires",
  "Initiation générale é l'informatique",
  "Initiation Excel",
  "Initiation tablettes électroniques / iPad",
  "Initiation et aide Espace membre",
  "Traitement de texte",
  "Montage PowerPoint",
  "Numérisation photos",
  "Initiation é Internet et courriel",
  "Conception site web",
  "Dépannage pour ordinateurs P.C.",
  "Dépannage pour ordinateurs Macintosh",
  "Installation de logiciels",
  "Dépannage disque dur",
  "Optimisation systéme d'exploitation (software)",
  "Transport besoins divers",
  "Transport pour les courses",
  "Transport moyenne distance",
  "Transport avec remorque",
  "Des bras pour moyen déménagement",
  "Des bras pour petit déménagement",
  "Aide pour préparer déménagement",
  "Ménage léger",
  "Lavage vitres",
  "Bricoleur pour petits travaux",
  "Menus travaux ébénisterie",
  "Aide pour rénovation",
  "Réparation de meubles",
  "Réparation appareils électroniques",
  "Entretien ou réparation automobile",
  "Lavage de voiture",
  "Réparation vélos",
  "Aide pour jardinage",
  "Conseils pour soins des arbres",
  "Conseils en aménagement paysager",
  "Travaux d'entretien de terrains",
  "Nettoyage saisonnier de terrains",
  "Cuisine plats ou repas",
  "Préparation repas é congeler",
  "Réparation ou restauration d'objets décoratifs",
  "Réparation bijoux",
  "Petites réparations vétements",
  "Rédaction textes en franéais",
  "Correction textes en anglais",
  "Apprentissage de l'anglais",
  "Conversation anglaise",
  "Initiation danse sociale",
  "Animation fétes et événements",
  "Reiki",
  "Massothérapie thérapeutique",
  "Massothérapie de détente",
  "Coupe cheveux",
  "Maquillage",
  "AccordeurE inscritE é la location solidaire (é titre d'information)",
  "Prét d'un objet location solidaire",
  "Accueil/réception permanence Accorderie",
  "Envoi postal pour L'Accorderie",
  "Facteur et factrice d'un jour",
  "Vérification comptable de L'Accorderie",
  "Rencontre de travail comité accueil",
  "Rencontre de travail comité gestion",
  "Communications pour L'Accorderie",
  "Comité accueil - coordination",
  "Session d'accueil de L'Accorderie",
  "Formation pour L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "Mise à jour de la liste des membres",
  "Tâches cléricales pour L'Accorderie",
  "Développement d'outils pour L'Accorderie",
  "Rencontre de travail aménagement / entretien des locaux",
  "Tâches cléricales comité de financement",
  "Aide démarches juridiques",
  "Dépannage pour ordinateurs P.C.",
  "Initiation retouche de photo informatisée",
  "Aide démarches juridiques",
  "Dépannage pour ordinateurs P.C.",
  "Initiation retouche de photo informatisée",
  "Bilan de santé naturopathique",
  "Bilan de santé naturopathique",
  "Initiation tablettes électroniques / iPad",
  "Initiation médias sociaux sur Internet",
  "Initiation cellulaires / téléphones intelligents",
  "Transport besoins divers",
  "Des bras pour gros déménagement",
  "Ménage léger",
  "Menus travaux ébénisterie",
  "Aide au désencombrement",
  "Correction textes en franéais",
  "Massage des pieds et mains",
  "Accueil/réception permanence Accorderie",
  "Comptabilité de L'Accorderie",
  "Comité Améliorons l'Accorderie",
  "Graphisme pour L'Accorderie",
  "Initiation tablettes électroniques / iPad",
  "Initiation médias sociaux sur Internet",
  "Initiation cellulaires / téléphones intelligents",
  "Transport besoins divers",
  "Des bras pour gros déménagement",
  "Ménage léger",
  "Menus travaux ébénisterie",
  "Aide au désencombrement",
  "Correction textes en franéais",
  "Massage des pieds et mains",
  "Accueil/réception permanence Accorderie",
  "Comptabilité de L'Accorderie",
  "Comité Améliorons l'Accorderie",
  "Graphisme pour L'Accorderie",
  "Accompagnement rendez-vous divers",
  "Accompagnement marche",
  "Garde d'enfants é votre maison",
  "Garde d'enfants é ma maison",
  "Garde de maison (home-sitting)",
  "Visite maison lors d'absence",
  "Garde d'animaux é votre maison",
  "Aide pour remplir formulaires",
  "Rapport d'impét personnel",
  "Initiation générale é l'informatique",
  "Initiation é Internet et courriel",
  "Recherche Internet",
  "Conception site web",
  "Installation Internet",
  "Initiation médias sociaux sur Internet",
  "Dépannage pour ordinateurs P.C.",
  "Dépannage disque dur",
  "Optimisation matériel informatique (hardware)",
  "Transcription enregistrement audio (verbatim)",
  "Initiation cellulaires / téléphones intelligents",
  "Transport besoins divers",
  "Transport pour les courses",
  "Transport de matériel avec voiture",
  "Des bras pour petit déménagement",
  "Ménage léger",
  "Peinture intérieure",
  "Bricoleur pour petits travaux",
  "Menus travaux plomberie",
  "Menus travaux électricité",
  "Conseils pour décoration intérieure",
  "Aménagement de l'espace maison",
  "Réparation électroménagers",
  "Réparation petits appareils électriques",
  "Aide pour jardinage",
  "Aide pour cuisiner",
  "Initiation fabrication de pain",
  "Petites réparations vétements",
  "Fabrication vétements en tricot",
  "Correction textes en franéais",
  "Montage vidéo",
  "Réalisation vidéo",
  "Coupe cheveux",
  "Envoi postal pour L'Accorderie",
  "Communications pour L'Accorderie",
  "Session d'accueil de L'Accorderie",
  "Tâches pour Fétes ou 5 é 7 de L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "Rencontre comité Vie associative et gestion de l'échange",
  "Mise à jour de la liste des membres",
  "Tâches manuelles pour L'Accorderie",
  "Tâches cléricales pour L'Accorderie",
  "Bon cadeau",
  "Accompagnement rendez-vous divers",
  "Accompagnement marche",
  "Garde d'enfants é votre maison",
  "Garde d'enfants é ma maison",
  "Garde de maison (home-sitting)",
  "Visite maison lors d'absence",
  "Garde d'animaux é votre maison",
  "Aide pour remplir formulaires",
  "Rapport d'impét personnel",
  "Initiation générale é l'informatique",
  "Initiation é Internet et courriel",
  "Recherche Internet",
  "Conception site web",
  "Installation Internet",
  "Initiation médias sociaux sur Internet",
  "Dépannage pour ordinateurs P.C.",
  "Dépannage disque dur",
  "Optimisation matériel informatique (hardware)",
  "Transcription enregistrement audio (verbatim)",
  "Initiation cellulaires / téléphones intelligents",
  "Transport besoins divers",
  "Transport pour les courses",
  "Transport de matériel avec voiture",
  "Des bras pour petit déménagement",
  "Ménage léger",
  "Peinture intérieure",
  "Bricoleur pour petits travaux",
  "Menus travaux plomberie",
  "Menus travaux électricité",
  "Conseils pour décoration intérieure",
  "Aménagement de l'espace maison",
  "Réparation électroménagers",
  "Réparation petits appareils électriques",
  "Aide pour jardinage",
  "Aide pour cuisiner",
  "Initiation fabrication de pain",
  "Petites réparations vétements",
  "Fabrication vétements en tricot",
  "Correction textes en franéais",
  "Montage vidéo",
  "Réalisation vidéo",
  "Coupe cheveux",
  "Envoi postal pour L'Accorderie",
  "Communications pour L'Accorderie",
  "Session d'accueil de L'Accorderie",
  "Tâches pour Fétes ou 5 é 7 de L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "Rencontre comité Vie associative et gestion de l'échange",
  "Mise à jour de la liste des membres",
  "Tâches manuelles pour L'Accorderie",
  "Tâches cléricales pour L'Accorderie",
  "Bon cadeau",
  "Accompagnement rendez-vous divers",
  "Accompagnement rendez-vous médicaux",
  "Accompagnement démarches suite é un décés",
  "Accompagnement magasinage",
  "Commissions é votre place",
  "Accompagnement épicerie",
  "Garde d'enfants é votre maison",
  "Tenue de livres comptables",
  "Rapport d'impét personnel",
  "Organisation et animation groupes de discussion",
  "Organisation événements sociaux",
  "Classement documents",
  "Communication interne",
  "Initiation générale é l'informatique",
  "Initiation Word",
  "Initiation Excel",
  "Initiation tablettes électroniques / iPad",
  "Recherche Internet",
  "Dépannage pour ordinateurs P.C.",
  "Transport besoins divers",
  "Transport pour les courses",
  "Transport moyenne distance",
  "Des bras pour petit déménagement",
  "Aide pour préparer déménagement",
  "Ménage léger",
  "Peinture intérieure",
  "Peinture extérieure",
  "Bricoleur pour petits travaux",
  "Menus travaux plomberie",
  "Aide pour rénovation",
  "Conseils pour décoration intérieure",
  "Aide pour jardinage",
  "Création ou élaboration d'un potager",
  "Travaux d'aménagement de terrains",
  "Taille de haie / arbustes",
  "Travaux d'entretien de terrains",
  "Nettoyage saisonnier de terrains",
  "Petit déneigement",
  "Aide cordage de bois",
  "Récupération outils usagés",
  "Travaux divers en hauteur",
  "Aide au désencombrement",
  "Cuisine plats ou repas",
  "Emballage cadeau",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Rédaction textes en franéais",
  "Correction textes en franéais",
  "Apprentissage de l'anglais",
  "Apprentissage de l'espagnol",
  "Initiation création littéraire",
  "Montage vidéo",
  "Prise de photos portrait",
  "Initiation photographie numérique",
  "Illustration",
  "Organisation petits événements",
  "Références fibromyalgie",
  "Reiki",
  "Massothérapie de détente",
  "Coupe cheveux",
  "Accueil/réception permanence Accorderie",
  "Rencontre de travail comité gestion",
  "Communications pour L'Accorderie",
  "Comité communications - rencontre et téches",
  "Comité mobilisation - rencontre et téches",
  "Animation kiosque pour L'Accorderie",
  "Représentation de L'Accorderie",
  "Session d'accueil de L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "élaboration du Journal / du Bottin",
  "Rencontre de travail pour journal",
  "Tâches cléricales pour L'Accorderie",
  "Développement d'outils pour L'Accorderie",
  "Tâche contact communautaire",
  "Rencontre comité jardin collectif",
  "Entretien jardin collectif",
  "Animation jardin collectif",
  "Soutien en informatique",
  "Appels de courtoisie",
  "Transfert d'heures",
  "Remboursement",
  "Accompagnement rendez-vous divers",
  "Accompagnement magasinage",
  "Commissions é votre place",
  "Garde d'enfants é votre maison",
  "Tenue de livres comptables",
  "Rapport d'impét personnel",
  "Organisation et animation groupes de discussion",
  "Organisation événements sociaux",
  "Classement documents",
  "Communication interne",
  "Initiation générale é l'informatique",
  "Initiation Word",
  "Initiation Excel",
  "Initiation tablettes électroniques / iPad",
  "Recherche Internet",
  "Dépannage pour ordinateurs P.C.",
  "Transport besoins divers",
  "Transport pour les courses",
  "Transport moyenne distance",
  "Des bras pour petit déménagement",
  "Aide pour préparer déménagement",
  "Ménage léger",
  "Peinture intérieure",
  "Peinture extérieure",
  "Bricoleur pour petits travaux",
  "Menus travaux plomberie",
  "Aide pour jardinage",
  "Création ou élaboration d'un potager",
  "Travaux d'entretien de terrains",
  "Nettoyage saisonnier de terrains",
  "Petit déneigement",
  "Aide cordage de bois",
  "Récupération outils usagés",
  "Aide au désencombrement",
  "Cuisine plats ou repas",
  "Emballage cadeau",
  "Petites réparations vétements",
  "Rédaction textes en franéais",
  "Apprentissage de l'anglais",
  "Initiation création littéraire",
  "Montage vidéo",
  "Prise de photos portrait",
  "Initiation photographie numérique",
  "Illustration",
  "Organisation petits événements",
  "Massothérapie de détente",
  "Coupe cheveux",
  "Accueil/réception permanence Accorderie",
  "Rencontre de travail comité gestion",
  "Comité communications - rencontre et téches",
  "Comité mobilisation - rencontre et téches",
  "Animation kiosque pour L'Accorderie",
  "Session d'accueil de L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "élaboration du Journal / du Bottin",
  "Rencontre de travail pour journal",
  "Tâches cléricales pour L'Accorderie",
  "Développement d'outils pour L'Accorderie",
  "Rencontre comité jardin collectif",
  "Entretien jardin collectif",
  "Animation jardin collectif",
  "Soutien en informatique",
  "Appels de courtoisie",
  "Transfert d'heures",
  "Remboursement",
  "Accompagnement rendez-vous divers",
  "Accompagnement démarches suite é un décés",
  "Accompagnement magasinage",
  "Accompagnement épicerie",
  "Garde d'enfants é votre maison",
  "Rapport d'impét personnel",
  "Classement documents",
  "Initiation générale é l'informatique",
  "Transport besoins divers",
  "Peinture extérieure",
  "Bricoleur pour petits travaux",
  "Aide pour rénovation",
  "Conseils pour décoration intérieure",
  "Aide pour jardinage",
  "Travaux d'aménagement de terrains",
  "Taille de haie / arbustes",
  "Travaux d'entretien de terrains",
  "Petit déneigement",
  "Travaux divers en hauteur",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Correction textes en franéais",
  "Apprentissage de l'espagnol",
  "Rencontre de travail comité gestion",
  "Comité mobilisation - rencontre et téches",
  "Représentation de L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "élaboration du Journal / du Bottin",
  "Rencontre de travail pour journal",
  "Tâche contact communautaire",
  "Soutien en informatique",
  "Accompagnement rendez-vous divers",
  "Accompagnement rendez-vous médicaux",
  "Ménage léger",
  "Travaux d'entretien de terrains",
  "Petites réparations vétements",
  "Références fibromyalgie",
  "Reiki",
  "Communications pour L'Accorderie",
  "Comité communications - rencontre et téches",
  "Comité mobilisation - rencontre et téches",
  "Représentation de L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Parrainage nouveaux AccordeurEs",
  "Développement d'outils pour L'Accorderie",
  "Tâche contact communautaire",
  "Accompagnement rendez-vous divers",
  "Accompagnement rendez-vous médicaux",
  "Accompagnement démarches médicales",
  "Accompagnement magasinage",
  "Commissions é votre place",
  "Accompagnement épicerie",
  "Accompagnement marche",
  "Garde d'animaux é votre maison",
  "Promenade chien",
  "Soins chat",
  "Toilettage chien",
  "Conseils démarrage entreprise",
  "Rapport d'impét personnel",
  "Rédaction Curriculum vitae",
  "Initiation générale é l'informatique",
  "Assistance probléme Internet",
  "Dépannage pour ordinateurs P.C.",
  "Initiation cellulaires / téléphones intelligents",
  "Assistance achat matériel informatique",
  "Transport besoins divers",
  "Transport moyenne distance",
  "Des bras pour gros déménagement",
  "Des bras pour moyen déménagement",
  "Des bras pour petit déménagement",
  "Ménage léger",
  "Lavage vitres",
  "Peinture intérieure",
  "Bricoleur pour petits travaux",
  "Menus travaux ébénisterie",
  "Menus travaux soudure",
  "Aide pour rénovation",
  "Gestion projet de rénovation",
  "Peinture décorative",
  "Accompagnement choix de décoration",
  "Réparations de petits moteurs électriques",
  "Réparation petits appareils électriques",
  "Réparation machine é coudre",
  "Entretien ou réparation automobile",
  "Réparation vélos",
  "Aide pour jardinage",
  "Entretien de plates-bandes",
  "Création ou élaboration d'un potager",
  "Aménagement paysager",
  "Petit déneigement",
  "Tonte de gazon",
  "Aide au désencombrement",
  "Aide pour cuisiner",
  "Cuisine plats ou repas",
  "Réparation ou restauration d'objets décoratifs",
  "Confection cartes de souhait artisanales",
  "Réparation bijoux",
  "Confection bijoux en matiéres recyclées",
  "Fabrication vétements",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Modifications vétements",
  "Couture de type industriel",
  "Réparation coussins, rideaux, housses douillettes",
  "Initiation usage de machine é coudre",
  "Foire artisanale",
  "- Foire de l'Artisanat",
  "Apprentissage de l'anglais",
  "Apprentissage de la guitare",
  "Chansonnier pour spectacle",
  "Initiation aquarelle",
  "Clown pour fétes d'enfants ou événements",
  "Reiki",
  "Harmonisation énergétique",
  "Massothérapie sur chaise",
  "Massothérapie de détente",
  "Méditation",
  "Aide dénichage d'aubaines",
  "Rencontre de travail comité accueil",
  "Comité accueil - équipe téléphone",
  "Formation pour L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Tâches manuelles pour L'Accorderie",
  "Rencontre de travail comité de financement",
  "Tâches diverses - Café",
  "Organisation et animation d'activités - milieux de vie dynamisés",
  "Réseau d'éclaireurs",
  "Projet Résilience",
  "APIC-Accompagnement d'aénés",
  "Appels de courtoisie",
  "Accompagnement rendez-vous divers",
  "Accompagnement rendez-vous médicaux",
  "Accompagnement magasinage",
  "Commissions é votre place",
  "Accompagnement épicerie",
  "Accompagnement marche",
  "Garde d'animaux é votre maison",
  "Promenade chien",
  "Soins chat",
  "Toilettage chien",
  "Conseils démarrage entreprise",
  "Rapport d'impét personnel",
  "Rédaction Curriculum vitae",
  "Initiation générale é l'informatique",
  "Assistance probléme Internet",
  "Dépannage pour ordinateurs P.C.",
  "Initiation cellulaires / téléphones intelligents",
  "Assistance achat matériel informatique",
  "Transport besoins divers",
  "Transport avec camionnette",
  "Des bras pour moyen déménagement",
  "Des bras pour petit déménagement",
  "Ménage léger",
  "Lavage vitres",
  "Peinture intérieure",
  "Bricoleur pour petits travaux",
  "Menus travaux ébénisterie",
  "Menus travaux soudure",
  "Aide pour rénovation",
  "Gestion projet de rénovation",
  "Peinture décorative",
  "Accompagnement choix de décoration",
  "Réparations de petits moteurs électriques",
  "Réparation petits appareils électriques",
  "Réparation machine é coudre",
  "Entretien ou réparation automobile",
  "Réparation vélos",
  "Aide pour jardinage",
  "Entretien de plates-bandes",
  "Création ou élaboration d'un potager",
  "Aménagement paysager",
  "Petit déneigement",
  "Tonte de gazon",
  "Aide au désencombrement",
  "Aide pour cuisiner",
  "Cuisine plats ou repas",
  "Réparation ou restauration d'objets décoratifs",
  "Réparation bijoux",
  "Confection bijoux en matiéres recyclées",
  "Fabrication vétements",
  "Coud bas de pantalon",
  "Petites réparations vétements",
  "Modifications vétements",
  "Couture de type industriel",
  "Réparation coussins, rideaux, housses douillettes",
  "Initiation usage de machine é coudre",
  "Foire artisanale",
  "- Foire de l'Artisanat",
  "Apprentissage de l'anglais",
  "Apprentissage de la guitare",
  "Chansonnier pour spectacle",
  "Initiation aquarelle",
  "Clown pour fétes d'enfants ou événements",
  "Reiki",
  "Harmonisation énergétique",
  "Massothérapie sur chaise",
  "Massothérapie de détente",
  "Méditation",
  "Aide dénichage d'aubaines",
  "Sondages pour L'Accorderie",
  "Rencontre de travail comité accueil",
  "Formation pour L'Accorderie",
  "Organisation / animation activité de L'Accorderie",
  "Tâches manuelles pour L'Accorderie",
  "Rencontre de travail comité de financement",
  "Tâches diverses - Café",
  "Organisation et animation d'activités - milieux de vie dynamisés",
  "Réseau d'éclaireurs",
  "Projet Résilience",
  "APIC-Accompagnement d'aénés",
  "Appels de courtoisie",
  "Accompagnement rendez-vous divers",
  "Transport moyenne distance",
  "Accompagnement démarches médicales",
  "Tâches diverses - Café",
  "Réseau d'éclaireurs",
  "Accompagnement rendez-vous divers",
  "Accompagnement rendez-vous médicaux",
  "Accompagnement pour courses et magasinage",
  "Accompagnement rendez-vous divers",
  "Accompagnement rendez-vous médicaux",
  "Accompagnement pour courses et magasinage",
];

export const alpha = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

export const userDataColumn = [
  { key: "id", header: "id" },
  { key: "age", header: "age" },
  { key: "genre", header: "genre" },
  { key: "revenu", header: "revenu" },
  { key: "region", header: "region" },
  { key: "ville", header: "ville" },
  { key: "arrondissement", header: "arrondissement" },
  { key: "accorderie", header: "accorderie" },
  { key: "mapid", header: "mapid" },
  { key: "address", header: "address" },
  { key: "longitude", header: "longitude" },
  { key: "latitude", header: "latitude" },
];

export const transactionDataColumn = [
  { key: "source", header: "source" },
  { key: "target", header: "target" },
  { key: "duree", header: "duree" },
  { key: "date", header: "date" },
  { key: "service", header: "service" },
  { key: "detailservice", header: "detailservice" },
  { key: "accorderie", header: "accorderie" },
  { key: "id", header: "id" },
];
